logger:
  dir: "/data/agent_backend/logs"
  level: "debug"

redis:
  host: "10.224.28.66"
  port: 6379
  db: 2
  password: 123456
  max_connections: 10

mongodb:
  host: "10.224.28.66"
  port: 19532
  database: "test"
  username: "copilot"
  password: "p3z8cjm*4B2O"
  auth_source: "admin"
  max_pool_size: 10
  min_pool_size: 1
  connect_timeout: 30000
  server_selection_timeout: 30000

# LLM 提供商配置
llm:
  default_provider: "deepseek"  # 默认使用 deepseek
  providers:
    deepseek:
      model: "deepseek-chat"
      temperature: 0.7
      streaming: true
      api_key_env: "DEEPSEEK_API_KEY"
      base_url: null
    
    openai:
      model: "gpt-4o"
      temperature: 0.7
      streaming: true
      api_key_env: "OPENAI_API_KEY"
      base_url: null
      
    claude:
      model: "claude-3-5-sonnet-20241022"
      temperature: 0.7
      streaming: true
      api_key_env: "ANTHROPIC_API_KEY"
      base_url: null
      
    moonshot:
      model: "moonshot-v1-8k"
      temperature: 0.7
      streaming: true
      api_key_env: "MOONSHOT_API_KEY"
      base_url: "https://api.moonshot.cn/v1"
      
    zhipu:
      model: "glm-4"
      temperature: 0.7
      streaming: true
      api_key_env: "ZHIPU_API_KEY"
      base_url: null
      
    qwen:
      model: "qwen-max"
      temperature: 0.7
      streaming: true
      api_key_env: "DASHSCOPE_API_KEY"
      base_url: null
      
    gemini:
      model: "gemini-pro"
      temperature: 0.7
      streaming: true
      api_key_env: "GOOGLE_API_KEY"
      base_url: null
